name: Backend lint and tests
run-name: ${{ github.event_name }} to ${{ github.ref_name }} by @${{ github.actor }}

env:
  path: ./prostoyoga/backend

on:
  push:
    paths:
      - ${{ env.path }}/**
  pull_request:
    paths:
      - ${{ env.path }}/**

jobs:
  linting_black:
    name: Linting with Black (Python${{ matrix.python-version }})
    strategy:
      matrix:
        python-version: [ "3.11", "3.12" ]
    uses: ./.github/workflows/black.yml
    with:
      python-version: ${{ matrix.python-version }}
      source_path: ${{ env.path }}

  linting_flake8:
    name: Linting with flake8 (Python${{ matrix.python-version }})
    strategy:
      matrix:
        python-version: [ "3.11", "3.12" ]
    uses: ./.github/workflows/flake8.yml
    with:
      source_path: ${{ env.path }}
      python-version: ${{ matrix.python-version }}

  typing_mypy:
    name: Checking static types with mypy (Python${{ matrix.python-version }})
    strategy:
      matrix:
        python-version: [ "3.11", "3.12" ]
    uses: ./.github/workflows/mypy.yml
    with:
      source_path: ${{ env.path }}
      python-version: ${{ matrix.python-version }}